version: '3.7'

services:
  frontend:
    container_name: frontend
    build: ./code/front
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000

  backend:
    container_name: backend
    build: ./code/Employee_management_system
    ports:
      - 8082:8082

